KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="Admin@123$"
    user_admin="Admin@123$"
    user_vinod="Welcome#123"
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="Admin@123$";
};
